export const productsJson = {
  display_headers: {
    id: false,
    image: true,
    sku: false,
    tags: false,
    name: true,
    inventory: true,
    status: true,
    case_qty: true,
    unit_wholesale_price: true,
    unit_retail_price: true,
  },
  product_info: [
    {
      id: 326,
      image:
        'http://local.tradamarket.com:3000/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEFDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2b7a4368985d630d30bad5e717d4cc584e18f31a/sample-1-7976.jpg',
      sku: ['A123', 'A124', 'A125', 'A126', 'A127', 'A128', 'A129', 'A130'],
      tags: '',
      name: 'Sample One',
      inventory: 'Quantity not set',
      status: true,
      case_qty: 5,
      unit_wholesale_price: '100.0',
      unit_retail_price: '500.0',
    },
    {
      id: 327,
      image:
        'http://local.tradamarket.com:3000/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEVDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ccf1cf5b0cd340b098334028326259d8a4bbd323/sample-2-7578.jpg',
      sku: ['A131'],
      tags: '',
      name: 'Sample 2',
      inventory: 'Quantity not set',
      status: true,
      case_qty: 10,
      unit_wholesale_price: '200.0',
      unit_retail_price: '600.0',
    },
    {
      id: 333,
      image:
        'http://local.tradamarket.com:3000/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWtDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1403d72ac1cd02aec1a149fd7e611568e7e44c49/sample-3-4479.jpg',
      sku: ['3XK'],
      tags: '',
      name: 'Sample 3',
      inventory: 'Quantity not set',
      status: true,
      case_qty: 3,
      unit_wholesale_price: '3.0',
      unit_retail_price: '3.0',
    },
    {
      id: 879,
      sku: ['BUR-3x5', 'BUR-4x6', 'BUR-5x5'],
      tags: 'Card,Birthday,Paper',
      name: 'Lil Burrito Card',
      inventory: 'Quantity not set',
      status: false,
      case_qty: 6,
      unit_wholesale_price: '2.5',
      unit_retail_price: '5.0',
    },
    {
      id: 878,
      sku: ['PHS-3x5', 'PHS-4x6', 'PHS-5x5'],
      tags: 'Card,Birthday,Paper',
      name: 'Next Phase Card',
      inventory: 'Quantity not set',
      status: false,
      case_qty: 6,
      unit_wholesale_price: '2.5',
      unit_retail_price: '5.0',
    },
    {
      id: 877,
      image:
        'http://local.tradamarket.com:3000/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnNKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7a4578ffd1b0f6aacf6b262c6bd94a259106e625/hot-shot-card-2341..jpg',
      sku: ['SHOT-3x5', 'SHOT-4x6', 'SHOT-5x5'],
      tags: 'Card,Birthday,Paper',
      name: 'Hot Shot Card',
      inventory: 'Out of stock',
      status: true,
      case_qty: 6,
      unit_wholesale_price: '2.5',
      unit_retail_price: '5.0',
    },
    {
      id: 876,
      sku: ['HNG-3x5', 'HNG-4x6', 'HNG-5x5'],
      tags: 'Card,Birthday,Paper',
      name: "Let's Hang Card",
      inventory: 'Quantity not set',
      status: false,
      case_qty: 6,
      unit_wholesale_price: '2.5',
      unit_retail_price: '5.0',
    },
    {
      id: 875,
      sku: ['CAC-3x5', 'CAC-4x6', 'CAC-5x5'],
      tags: 'Card,Birthday,Paper',
      name: 'Cactus Thank You Card',
      inventory: 'Quantity not set',
      status: false,
      case_qty: 5,
      unit_wholesale_price: '2.5',
      unit_retail_price: '5.0',
    },
    {
      id: 874,
      sku: ['PUP-3x5', 'PUP-4x6', 'PUP-5x5', 'PUP-5x7'],
      tags: 'Card,Birthday,Paper',
      name: 'Holiday Pup Card',
      inventory: 'Quantity not set',
      status: false,
      case_qty: 9,
      unit_wholesale_price: '2.5',
      unit_retail_price: '5.0',
    },
  ],
};
